### ISSUE TITLE
Backlight works but keys don't

### ISSUE THREAD

**Issue by hairydawgy** [JasonRivers/arduino-ATEM-xkeys#1]
Nice job!  I am attempting to do something similar, but I am having some connectivity issues.  I am using an XK-24 attached to an Arduino Mega ADK and attempting to use the xkeys_demo and backlight_tester examples. The xkeys_demo lights all keys blue, but I see nothing when pressing keys. The backlight_tester cycles the LEDs, but no key events seen there either. Any ideas?

**Comment by JasonRivers** [comment]
Hi.

I've not had this issue, but did you set the XKs.padsize up? If not you probably want to set that to 24, otherwise things go a little odd. On a note for this, checkout the layout here:https://github.com/tstrausb/XKeys-Library-for-Arduino I'm not sure how the layout will actually be setup on the XK24, what I do know is the XK60 you actually need to set up with 80 keys, and ignore the ones it doesn't have.

I have also taken a fork of the XKeys-Library here https://github.com/JasonRivers/XKeys-Library-for-Arduino Checkout the usbhid-fixes branch, I've updated the library to work with the new arduino HID libraries.

In my code, I checked for keypresses and wrote messages on the Serial for each press manually, you might want to give that a go.

Sorry for the late reply, things have been busy with preparing some of this for our own conference.

Jason.

**Comment by hairydawgy** [comment]
Jason,
Thanks for the reply; I too have been very busy lately.

 I have it working; unfortunately, I don't know exactly what was causing the issue.  To resolve, I ended up completely removing the Arduino application and all libraries and re-installing everything. 

Best,
Lee

**Comment by JasonRivers** [comment]
Glad you got it working, Let me know if you have other issues, I'll be picking this code up again in the next few weeks.
